### ISSUE TITLE
TypeError: _activity.runOnUiThread is not a function

### ISSUE THREAD

**Issue by bigmeech** [mkloubert/nativescript-social-login#18]
Hi.

I'm getting `_activity.runOnUiThread is not a function` when i call loginWithFacebook for android.

I'm build with nativescript version 3.0.3. Is plugin compatible with the latest version of nativescript?

**Comment by bigmeech** [comment]
Fixed! 
i wasnt passing the correct object containing the activity object to the init function.

Closing...
